feat(apollo-smith): implement a graphql test case generator
apollographql/apollo-rs pull request #168
Opened 2022-02-10 13:59 UTC by bnjjj

close #114 
close #155 
close #156

2022-02-15 16:01 UTC, lrlna requested changes
`apollo-smith` is looking really really good. Super excited to land this!

There are two main things I noticed in this current state:
- I don't see "ignored token" implementation in the test case generator. I bet we are going to find a whole lot of bugs while fuzzing once this is added.
- Similar to a comment I made in the encoder PR, Operation Definition can have a shorthand, and the test case generator should account for it. The shorthand is only valid when it's the only Operation Definition in a given Document.

2022-02-16 10:22 UTC, bnjjj commented on fuzz/fuzz_targets/parser.rs
> +        debug!("========================");
Oh yes you're talking about `log_gql_doc` function. I forgot to add it when there is an error. It's done now. And about the `debug!` logging it's just useful when you're debugging or developing `apollo-smith` to see what you're generating.

2022-02-16 14:05 UTC, bnjjj commented on crates/apollo-smith/src/lib.rs
> +        };
Created https://github.com/apollographql/apollo-rs/issues/173

2022-02-17 12:09 UTC, lrlna approved these changes
Exciting!

2022-02-17 12:13 UTC, merged