resource bound parsing execution
apollographql/apollo-rs pull request #239
Opened 2022-06-01 10:40 UTC by garypen

This PR introduces a general purpose resource bounding framework for the
parser. The framework illustrates how it can be used with the provision
of a "selection" limiting mechanism and the introduction of a
ParserLimits data structure which encapsulates the limiting behaviour.

I ran the benchmarks with/without my changes and the overhead was not
statistically significant.

Open Questions/Comments:

1. Do we want to print limits as part of our SyntaxTree? I note that we
   print errors there, so I've tried to treat limits in a similiar way
   to how errors are treated, but maybe that's not the neatest approach.

   This is probably the bit that needs more thought/attention. What's
   the best way to deal with limits? Because parse() consumes the
   parser to generate a syntax tree, our options for exposing limits are
   "limited" (sorry). I didn't want to add a new method
   (parse_yield_limits()?) or change the current parse() signature if I
   could avoid that.

2. I've declared ParserLimits and LimitTracker to be Copy, because I
   want using them to be simple and I can't think of a good reason why
   a limit won't be Copy. I'm happy to change this if there's a
   good reason to do so.

3. I considered making the limits optional, but concluded it was cleaner
   to always have limits, but make the defaults "high". It's debatable
   what the default "high" should be, but I've left it set to usize::MAX
   for now. You'd hit a stack overflow long before you reached that
   level, but it's a placeholder.

   The other reason for not making limits optional is that I believe at
   some point we'll always want limits for the parser, so establishing
   them now is a good starting point.

4. Some of the components may seem to be a bit over-engineered for the
   current simple requirements, but I think it's a good idea to put the
   framework in place and I imagine that we may need additional limits
   soon enough.
fixes: #225

2022-06-01 12:34 UTC, lrlna requested changes
> This is probably the bit that needs more thought/attention. What's
the best way to deal with limits? Because parse() consumes the
parser to generate a syntax tree, our options for exposing limits are
"limited" (sorry). I didn't want to add a new method
(parse_yield_limits()?) or change the current parse() signature if I
could avoid that.

I don't think we should change the `parser.parse()` signature. At the moment, having `ast.recursion_limit()` getter seems marginally better. Something to consider though is `ast.recursion_limit()` function is solely for the purpose of temporary logging in the router. Is there a way for the router to infer that information from the recursion limit error message? That way we don't have to expose this new getter at all. 

>I considered making the limits optional, but concluded it was cleaner
to always have limits, but make the defaults "high". It's debatable
what the default "high" should be, but I've left it set to usize::MAX
for now. You'd hit a stack overflow long before you reached that
level, but it's a placeholder.
>
>The other reason for not making limits optional is that I believe at
some point we'll always want limits for the parser, so establishing
them now is a good starting point.

No, I agree, having a default recursion limit is good. I left a note in one of the comments of making it 100 for now. I prefer users to get an error message rather a stack overflow panic.

>Some of the components may seem to be a bit over-engineered for the
current simple requirements, but I think it's a good idea to put the
framework in place and I imagine that we may need additional limits
soon enough.

What other limits do you see the parser needing in the future? The way GraphQL grammar is defined SelectionSet is the only place for recursive parsing. Is there something else you can see us needing?

2022-06-01 15:43 UTC, garypen commented on crates/apollo-parser/src/parser/mod.rs
> +    limits: ParserLimits,
done: b2ae1d0d6237d2f0e2fba4b51f015379f2fcd230

2022-06-01 15:45 UTC, garypen commented on crates/apollo-parser/src/parser/mod.rs
> +pub struct ParserLimits {
ParserLimits no longer exists, so:
done: b2ae1d0d6237d2f0e2fba4b51f015379f2fcd230
(although, now we expose TrackerLimit in the public interface)

2022-06-01 15:46 UTC, garypen commented on crates/apollo-parser/src/parser/mod.rs
> +    /// are silently discarded.
We discussed this and concluded this implementation seems like the best approach right now and could be improved in the future if we figure out how to do that.

2022-06-01 15:47 UTC, garypen commented on crates/apollo-parser/src/parser/mod.rs
> +        self.accept_errors = false;
Still required with the current approach.

2022-06-01 15:47 UTC, garypen commented on crates/apollo-parser/src/parser/syntax_tree.rs
> +    pub fn limits(&self) -> ParserLimits {
ParserLimits is a copy type, so ...

2022-06-01 15:47 UTC, garypen commented on crates/apollo-parser/src/parser/syntax_tree.rs
> +    pub(crate) limits: ParserLimits,
done: b2ae1d0d6237d2f0e2fba4b51f015379f2fcd230

2022-06-01 15:48 UTC, garypen commented on crates/apollo-parser/src/parser/syntax_tree.rs
> +        print_limits(f, self.limits)
done: b2ae1d0d6237d2f0e2fba4b51f015379f2fcd230

(I renamed it to `print_recursion_limit`)

2022-06-01 15:49 UTC, garypen commented on crates/apollo-parser/src/parser/syntax_tree.rs
> +    pub fn limits(&self) -> ParserLimits {
I'm going to mark this as resolved because it seems ok to not return reference to small `Copy` type.

2022-06-01 15:51 UTC, garypen commented on crates/apollo-parser/src/parser/mod.rs
> +            limit: usize::MAX,
We figured a fairly safe value from the usage we've had in the router is `4_096`. In testing, we observed stack overflow issues with `tokio` (which has a small stack) at about `12_000`.

I'd be happy to set this to `4_096`, but happy to go lower if you think that's feasible. Note: Still at usize::MAX.

2022-06-07 15:59 UTC, lrlna commented on crates/apollo-parser/src/parser/mod.rs
> +            limit: usize::MAX,
let's do the value you've seen in the router of `4_096`

2022-06-07 16:28 UTC, lrlna commented on crates/apollo-parser/src/parser/mod.rs
> +pub struct LimitTracker {
Alright, let's expose it then. What do you think about directly naming it `RecursionLimitTracker`?

2022-06-07 16:58 UTC, lrlna approved these changes

2022-06-08 07:24 UTC, merged