feat(compiler): variable usage is allowed
apollographql/apollo-rs pull request #537
Opened 2023-04-25 17:14 UTC by lrlna

closes #312 

This looks at currently defined variables and compares them to how they are used, [spec](https://spec.graphql.org/October2021/#sec-All-Variable-Usages-are-Allowed).

2023-04-25 17:20 UTC, lrlna commented on crates/apollo-compiler/src/validation/fragment.rs
> +    diagnostics.extend(db.validate_selection_set(def.selection_set().clone(), var_defs));
The consequence of moving `db.validate_fragment_definition` to be run during selection validation is that we somehow end up missing some field validation inside a fragment definition's selection set! really confused on why that's happening

2023-04-25 17:20 UTC, lrlna commented on crates/apollo-compiler/test_data/diagnostics/0089_fragment_type_condition_on_non_existent_types.txt
> +    },
I feel like this diagnostic here should not be here! something went astray with fragment validation 😬

2023-04-25 17:20 UTC, lrlna commented on crates/apollo-compiler/test_data/diagnostics/0090_fragment_spread_impossible.txt
something went wrong with validation here also, as these diagnostics should definitely be here!

2023-04-26 08:07 UTC, lrlna commented on crates/apollo-compiler/test_data/diagnostics/0088_fragment_selection_set.graphql
> +    }
the fragment won't try to be validated if we don't call it, so calling it again inside a correct field

2023-04-26 08:08 UTC, lrlna commented on crates/apollo-compiler/test_data/diagnostics/0090_fragment_spread_impossible.graphql
@goto-bus-stop can you triple check that validations for this test are correct? i had to add a query to call these fragments, but am not sure if that produces the right diagnostics

2023-04-26 08:09 UTC, lrlna commented on crates/apollo-compiler/src/validation/fragment.rs
> +    diagnostics.extend(db.validate_selection_set(def.selection_set().clone(), var_defs));
fixed this bit!

2023-04-26 08:09 UTC, lrlna commented on crates/apollo-compiler/test_data/diagnostics/0089_fragment_type_condition_on_non_existent_types.txt
> +    },
fixed this also!

2023-04-26 08:09 UTC, lrlna commented on crates/apollo-compiler/test_data/diagnostics/0090_fragment_spread_impossible.txt
also fixed

2023-05-04 14:32 UTC, goto-bus-stop requested changes
Looks great! \ :grin: /

2023-05-04 14:32 UTC, goto-bus-stop commented on crates/apollo-compiler/test_data/diagnostics/0006_subscription_with_multiple_root_fields_in_inline_fragments.txt
> +    },
to keep this test focused on just the multiple root fields diagnostic, maybe we should define `disallowedSecondRootField` in `type Subscription`?

2023-05-08 10:17 UTC, lrlna commented on crates/apollo-compiler/src/validation/variable.rs
> +fn are_types_compatible(location_ty: &hir::Type, variable_ty: &hir::Type) -> bool {
ah good catch, yes let's

2023-05-08 11:58 UTC, lrlna commented on crates/apollo-compiler/src/validation/variable.rs
> +    };
yea!

2023-05-08 14:32 UTC, merged